#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
JSON Utils - JSON parsing utilities
Specifically for extracting and parsing JSON data from LLM output,
supports Markdown code block processing and is robust to Python
triple-quoted strings generated by LLMs.
"""

import json
import re
from typing import Any

# Pre-compiled regex patterns
_TRIPLE_QUOTED_STRING_PATTERN = re.compile(r'"""([\s\S]*?)"""')
_CODE_BLOCK_PATTERN = re.compile(r"```(?:json)?\s*([\s\S]*?)\s*```")
_JSON_OBJ_PATTERN = re.compile(r"\{[\s\S]*\}")
_JSON_ARR_PATTERN = re.compile(r"\[[\s\S]*\]")
_ILLEGAL_CONTROL_CHARS_PATTERN = re.compile(r"[\x00-\x1f\x7f-\x9f]")


def _escape_triple_quoted_strings(text: str) -> str:
    """
    Convert Python triple-quoted strings (\"\"\" ... \"\"\")
    into JSON-safe escaped strings.

    This fixes cases where LLMs generate Python code inside JSON,
    which would otherwise violate JSON syntax.
    """

    def replacer(match: re.Match) -> str:
        content = match.group(1)
        # json.dumps safely escapes newlines and quotes
        return json.dumps(content)

    return _TRIPLE_QUOTED_STRING_PATTERN.sub(replacer, text)


def extract_json_from_text(text: str) -> dict[str, Any] | list[Any] | None:
    """
    Extract JSON object or array from text.

    Supports:
    1. ```json ... ``` code blocks
    2. ``` ... ``` code blocks
    3. Pure JSON text
    4. JSON containing Python triple-quoted strings (sanitized)

    Args:
        text: Original text containing JSON

    Returns:
        Parsed JSON object (dict) or array (list),
        or None if parsing fails.
    """
    if not text:
        return None

    # 🔧 FIX: sanitize triple-quoted strings before any JSON parsing
    text = _escape_triple_quoted_strings(text)

    # 1. Try matching Markdown code blocks
    match = _CODE_BLOCK_PATTERN.search(text)

    if match:
        json_str = match.group(1).strip()
        try:
            return json.loads(json_str)
        except json.JSONDecodeError:
            pass

    # 2. Try parsing the full text directly
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # 3. Try extracting outermost JSON object
    match_obj = _JSON_OBJ_PATTERN.search(text)
    if match_obj:
        try:
            return json.loads(match_obj.group(0))
        except json.JSONDecodeError:
            pass

    # 4. Try extracting outermost JSON array
    match_arr = _JSON_ARR_PATTERN.search(text)
    if match_arr:
        try:
            return json.loads(match_arr.group(0))
        except json.JSONDecodeError:
            pass

    return None


def clean_json_string(json_str: str) -> str:
    """
    Clean JSON string by removing illegal control characters.
    """
    return _ILLEGAL_CONTROL_CHARS_PATTERN.sub("", json_str)
